Add support for PlaceholderAPI
serversigns/ServerSigns pull request #3
Opened 2019-07-24 22:51 UTC by SeDark

Added compatibility with placeholderAPI

Example:

/svs add <if> placeholder:%luckperms_has_permission_somePermission%=yes
/svs add <msg> OK
/svs add <endif>

////

/svs add <if> placeholder:%player_name%=Seruhio|Peter|NickName
/svs add <msg> OK
/svs add <endif>

2019-07-25 17:32 UTC, EpiCanard commented
I think you can reformat all your changes you have a mix of tab and spaces.
The format of other files is 4 spaces.

2019-07-25 18:26 UTC, amnrmain commented
> I think you can reformat all your changes you have a mix of tab and spaces.
> The format of other files is 4 spaces.

Sure :)

2019-07-25 18:27 UTC, SeDark commented
> I think you can reformat all your changes you have a mix of tab and spaces.
> The format of other files is 4 spaces.

Sure :)

2019-07-25 21:12 UTC, EpiCanard commented
Good work, thank you :)

2019-07-25 21:47 UTC, CalibeR50 commented
This sounds like a nice addition, thanks for the PR. It would need some additions to the external documentation tho.
I'll leave this open for now while I discuss further steps with Exloki. We definitely need a new Maintainer, as neither of us is active in MC right now.

2019-09-03 12:29 UTC, EpiCanard commented
Any news ?

2019-09-23 19:33 UTC, EpiCanard commented
@CalibeR50  Can we at least merge this Pull Request please ? This feature opens many possibilities that we sadly can not use for the moment.

Thanks in advance for you answer

2019-09-23 20:10 UTC, SeruhioX commented
I think this feature is essential for this plugin, as it adds infinite possibilities.

I was waiting a long time for the author to add it and asked several times... When the code was published I opened this request since someone had to do it.

We will continue waiting for an answer.

Greetings

2019-09-24 19:14 UTC, CalibeR50 commented
Hi, 

I think, as long as nobody actively maintains the project, pull requests for features are not really important, especially if those involve additional third party dependencies. The features would neither be documented nor released, which is why I don't currently want to accept the PR.
If you need the features yourself, you can easily build svs with the respective features on your local machine.

If one is willing to take over maintaining the project, I'd be happy to provide the necessary resources to get this going again.

I hope you can understand my reasoning here.

Greetings

2019-09-27 20:32 UTC, EpiCanard commented
Hello

If you agree, I would like to continue to actively maintains the project. This plugin must continue to live.
I will make sure that the project continues to work properly, update the documentation regularly and answer questions from the players.

Thanks in advance for your answer

Best regards

2019-10-02 09:34 UTC, CalibeR50 commented
Hi, 

sounds great. Can you leave me a message at svs@czymm.de with your discord? I guess we can discuss anything further there.

Greetings

2019-10-09 20:24 UTC, EpiCanard requested changes
You forgot dependency to PlaceholderAPI in pom.xml, can you add it ?

2019-10-09 20:24 UTC, EpiCanard commented on src/main/java/de/czymm/serversigns/hooks/HookManager.java
> +            ServerSignsPlugin.log("Unable to load PlaceholderAPI dependency - placeholder features will be disabled");
Can you add a link to PlaceholderAPI download ? https://www.spigotmc.org/resources/placeholderapi.6245/

2019-10-09 20:24 UTC, EpiCanard commented on src/main/java/de/czymm/serversigns/hooks/PlaceholderAPIHook.java
> +        if (Bukkit.getPluginManager().getPlugin("PlaceholderAPI") == null) {
Can you add a condition to check if PlaceholderAPI is disabled ?

2019-10-09 20:24 UTC, EpiCanard commented on src/main/java/de/czymm/serversigns/parsing/operators/PlaceholderOperator.java
> +        return new ParameterValidityResponse(isValid, "Parameter must be in the format <placeholder>=<match>");
Can you add support of > and < for number only ?
That we can support comparison between number ?

2019-10-09 20:28 UTC, EpiCanard requested changes

2019-10-09 20:28 UTC, EpiCanard commented on src/main/java/de/czymm/serversigns/parsing/operators/PlaceholderOperator.java
> +package de.czymm.serversigns.parsing.operators;
Can you add GNU Licence header please ?

2019-11-16 16:51 UTC, Segysmundo commented
Hey there, SeruhioX appears to be abroad with his job and won't be able to take care of this any time soon.

Do you think you would be able to implement this on your own?

2019-11-17 18:17 UTC, EpiCanard commented
I can do it but I don't have much free time right now to apply the requested changes.

2020-01-05 17:52 UTC, EpiCanard commented
I merge to **feature/placeholderApi** to continue myself the work.

2020-01-05 17:53 UTC, merged